name: mpc-qt
version: 18.03
# version-script: cat $SNAPCRAFT_STAGE/version
summary: A clone of Media Player Classic reimplemented in Qt.
description: |
  Media Player Classic Home Cinema (mpc-hc) is considered by many to be the quintessential media player for the Windows desktop. Media Player Classic Qute Theater (mpc-qt) aims to reproduce most of the interface and functionality of mpc-hc while using libmpv to play video instead of DirectShow.

grade: devel
confinement: devmode
architectures:
  - build-on: amd64
    run-on: [amd64]

parts:
  desktop-qt5:
    source-tag: v20180201
  mpc-qt:
    plugin: qmake
    source: https://github.com/cmdrkotori/mpc-qt
    source-type: git
    after:
      - desktop-qt5
    stage-packages:
      - mpv
      - libqt5x11extras5
      - libvdpau-va-gl1
    build-packages:
      - qtcreator
      - qt5-default
      - libqt5x11extras5-dev
      - qttools5-dev-tools
      - libmpv-dev

apps:
  mpc-qt:
    command: desktop-launch $SNAP/usr/bin/mpc-qt
    desktop: 'usr/share/applications/Media Player Classic Qute Theater.desktop'
    plugs:
      - x11
      - home
      - unity7
      - network
      - desktop
      - opengl
      - wayland
      - pulseaudio
      - mount-observe
      - desktop-legacy
      - removable-media
      - screen-inhibit-control
    slots:
      - mpris
