name: mpc-qt
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: A clone of Media Player Classic reimplemented in Qt.
description: |
  Media Player Classic Home Cinema (mpc-hc) is considered by many to be the quintessential media player for the Windows desktop. Media Player Classic Qute Theater (mpc-qt) aims to reproduce most of the interface and functionality of mpc-hc while using libmpv to play video instead of DirectShow.

grade: devel
confinement: devmode
architectures:
  - build-on: amd64
    run-on: [amd64]

parts:
  desktop-qt5:
    source-tag: v20180201
  ppa:
    plugin: nil
    override-build: |
      snapcraftctl build
      add-apt-repository ppa:mc3man/mpv-tests -y
      apt update
    build-packages:
      - software-properties-common
  mpc-qt:
    plugin: qmake
    source: https://github.com/cmdrkotori/mpc-qt
    source-type: git
    after:
      - ppa
      - desktop-qt5
    override-build: |
      snapcraftctl build
      qmake-qt5 PREFIX=/usr mpc-qt.pro \
        QMAKE_CFLAGS_RELEASE="${CFLAGS}" \
        QMAKE_CXXFLAGS_RELEASE="${CXXFLAGS}" \
        QMAKE_LFLAGS_RELEASE="${LDFLAGS}"
      set -ex
      ver=$(wget https://software.opensuse.org/package/mpc-qt -q -S -O - 2>&1 | grep Leap | grep mpc-qt | sed '1,11d;13,18d;s|href="||g;s|">64||g' | awk '{print $3}' | sed -n 's/.*mpc-qt//p' | cut -c02-06)
      echo $ver > $SNAPCRAFT_STAGE/version
    stage-packages:
      - mpv
      - libqt5x11extras5
      - libvdpau-va-gl1
    build-packages:
      - qtcreator
      - qt5-default
      - libqt5x11extras5-dev
      - qttools5-dev-tools
      - libmpv-dev
      - wget

apps:
  mpc-qt:
    command: desktop-launch $SNAP/usr/bin/mpc-qt
    desktop: 'usr/share/applications/Media Player Classic Qute Theater.desktop'
    plugs:
      - x11
      - home
      - unity7
      - network
      - desktop
      - opengl
      - wayland
      - pulseaudio
      - mount-observe
      - desktop-legacy
      - removable-media
      - screen-inhibit-control
    slots:
      - mpris
