name: mpc-qt
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: A clone of Media Player Classic reimplemented in Qt.
description: |
  Media Player Classic Home Cinema (mpc-hc) is considered by many to be the quintessential media player for the Windows desktop. Media Player Classic Qute Theater (mpc-qt) aims to reproduce most of the interface and functionality of mpc-hc while using libmpv to play video instead of DirectShow.

grade: devel
confinement: devmode
architectures:
  - build-on: amd64
    run-on: [amd64]

parts:
  desktop-qt5:
    stage:
      - -usr/share/doc
      - -usr/share/man
      - -usr/share/lintian
      - -etc/fonts/conf.avail/10-antialias.conf
      - -etc/fonts/conf.avail/10-hinting-full.conf
      - -etc/fonts/conf.avail/10-hinting-medium.conf
      - -etc/fonts/conf.avail/10-hinting-slight.conf
      - -etc/fonts/conf.avail/30-metric-aliases.conf
      - -etc/fonts/conf.avail/40-nonlatin.conf
      - -etc/fonts/conf.avail/45-latin.conf
      - -etc/fonts/conf.avail/53-monospace-lcd-filter.conf
      - -etc/fonts/conf.avail/60-latin.conf
      - -etc/fonts/conf.avail/65-nonlatin.conf
      - -etc/fonts/fonts.conf
      - -lib/udev/hwdb.d/90-libinput-model-quirks.hwdb
      - -lib/udev/libinput-device-group
      - -lib/udev/libinput-model-quirks
      - -lib/udev/rules.d/90-libinput-model-quirks.rules
      - -usr/bin/fc-cache
      - -usr/bin/fc-cat
      - -usr/bin/fc-list
      - -usr/bin/fc-match
      - -usr/bin/fc-pattern
      - -usr/bin/fc-query
      - -usr/bin/fc-scan
      - -usr/bin/fc-validate
      - -usr/lib/x86_64-linux-gnu/libQt5Network.so.5*
      - -usr/lib/x86_64-linux-gnu/libQt5DBus.so.5*
      - -usr/lib/x86_64-linux-gnu/libQt5Gui.so.5*
      - -usr/lib/x86_64-linux-gnu/libQt5Core.so.5*
      - -usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5*
      - -usr/lib/x86_64-linux-gnu/libQt5X11Extras.so.5*
      - -usr/lib/x86_64-linux-gnu/libQt5EglDeviceIntegration.so.5*
      - -usr/lib/x86_64-linux-gnu/libQt5Svg.so.5*
      - -usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5*
      - -usr/lib/x86_64-linux-gnu/libwayland-client.so.0.3.0
      - -usr/lib/x86_64-linux-gnu/libwayland-cursor.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libwayland-server.so.0.1.0
      - -usr/lib/x86_64-linux-gnu/libxkbcommon-x11.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libxkbcommon.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/qt5/plugins/bearer/libqconnmanbearer.so
      - -usr/lib/x86_64-linux-gnu/qt5/plugins/bearer/libqgenericbearer.so
      - -usr/lib/x86_64-linux-gnu/qt5/plugins/bearer/libqnmbearer.so
      - -usr/lib/x86_64-linux-gnu/qt5/plugins/egldeviceintegrations/libqeglfs-kms-integration.so
      - -usr/lib/x86_64-linux-gnu/qt5/plugins/egldeviceintegrations/libqeglfs-x11-integration.so
      - -usr/lib/x86_64-linux-gnu/qt5/plugins/generic/libqevdevkeyboardplugin.so
      - -usr/lib/x86_64-linux-gnu/qt5/plugins/generic/libqevdevmouseplugin.so
      - -usr/lib/x86_64-linux-gnu/qt5/plugins/generic/libqevdevtabletplugin.so
      - -usr/lib/x86_64-linux-gnu/qt5/plugins/generic/libqevdevtouchplugin.so
      - -usr/lib/x86_64-linux-gnu/qt5/plugins/generic/libqlibinputplugin.so
      - -usr/lib/x86_64-linux-gnu/qt5/plugins/generic/libqtuiotouchplugin.so
      - -usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqgif.so
      - -usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqico.so
      - -usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqjpeg.so
      - -usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so
      - -usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so
      - -usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqeglfs.so
      - -usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqlinuxfb.so
      - -usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimal.so
      - -usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimalegl.so
      - -usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqoffscreen.so
      - -usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
      - -usr/lib/x86_64-linux-gnu/qt5/plugins/xcbglintegrations/libqxcb-egl-integration.so
      - -usr/lib/x86_64-linux-gnu/qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so

  ppa:
    plugin: nil
    override-build: |
      snapcraftctl build
      add-apt-repository ppa:mc3man/mpv-tests -y
      add-apt-repository ppa:jonathonf/ffmpeg-3 -y
      apt-add-repository http://archive.neon.kde.org/user -y
      wget -q -O - http://archive.neon.kde.org/public.key | apt-key add -
      apt update
      apt upgrade -y && apt install -f -y
    build-packages:
      - software-properties-common
      - wget
  mpc-qt:
    plugin: nil
    after:
      - ppa
      - desktop-qt5
    override-build: |
      snapcraftctl build
      set -ex
      ver=$(wget https://software.opensuse.org/package/mpc-qt -q -S -O - 2>&1 | grep Leap | grep mpc-qt | sed '1,11d;13,18d;s|href="||g;s|">64||g' | awk '{print $3}' | sed -n 's/.*mpc-qt//p' | cut -c02-06)
      echo $ver > $SNAPCRAFT_STAGE/version
      mpcurl=$(wget https://software.opensuse.org/package/mpc-qt -q -S -O - 2>&1 | grep Leap | grep mpc-qt | sed '1,11d;13,18d;s|href="||g;s|">64||g' | awk '{print $3}')
      wget $mpcurl
      rpm2cpio mpc-qt*.rpm | cpio -idmv
      cp 'usr/share/applications/Media Player Classic Qute Theater.desktop' usr/share/applications/mpc-qt.desktop
      rm 'usr/share/applications/Media Player Classic Qute Theater.desktop' && cp -R -p usr $SNAPCRAFT_PART_INSTALL
      sed -i 's|Icon=mpc-qt|Icon=/usr/share/pixmaps/mpc-qt\.svg|' $SNAPCRAFT_PART_INSTALL/usr/share/applications/mpc-qt.desktop
    stage-packages:
      - mpv
      - libmpv1
      - libqt5core5a
      - libqt5gui5
      - libqt5network5
      - libqt5quickwidgets5
      - libqt5x11extras5
      - libvdpau-va-gl1
      - libgl1-mesa-glx
      - libglu1-mesa
    build-packages:
      - wget
      - rpm2cpio
      - cpio
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/share/lintian

apps:
  mpc-qt:
    command: desktop-launch $SNAP/usr/bin/mpc-qt
    desktop: usr/share/applications/mpc-qt.desktop
    plugs:
      - x11
      - home
      - unity7
      - network
      - desktop
      - opengl
      - wayland
      - pulseaudio
      - mount-observe
      - desktop-legacy
      - removable-media
      - screen-inhibit-control
    slots:
      - mpris
