name: mpc-qt
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: A clone of Media Player Classic reimplemented in Qt.
description: |
  Media Player Classic Home Cinema (mpc-hc) is considered by many to be the quintessential media player for the Windows desktop. Media Player Classic Qute Theater (mpc-qt) aims to reproduce most of the interface and functionality of mpc-hc while using libmpv to play video instead of DirectShow.

grade: devel
confinement: strict
architectures:
  - build-on: amd64
    run-on: [amd64]
base: core18

parts:
  ppa:
    plugin: nil
    override-build: |
      snapcraftctl build
      add-apt-repository ppa:mc3man/mpv-tests -y
      add-apt-repository ppa:jonathonf/ffmpeg-4 -y
      apt update
    build-packages:
      - software-properties-common
      - wget
  mpc-qt:
    plugin: nil
    after:
      - ppa
      - desktop-qt5
    override-build: |
      snapcraftctl build
      set -ex
      ver=$(wget https://software.opensuse.org/package/mpc-qt -q -S -O - 2>&1 | grep "Leap_15" | sed 's|="| |g;s|"| |g;3,6d;1d;s/.*mpc-qt-//g;s|-| |g' | awk '{print $1}')
      echo $ver > $SNAPCRAFT_STAGE/version
      mpcurl=$(wget https://software.opensuse.org/package/mpc-qt -q -S -O - 2>&1 | grep "Leap_15" | sed 's|="| |g;s|"| |g;3,6d;1d' | awk '{print $5}')
      wget $mpcurl
      rpm2cpio mpc-qt*.rpm | cpio -idmv
      cp 'usr/share/applications/Media Player Classic Qute Theater.desktop' usr/share/applications/mpc-qt.desktop
      rm 'usr/share/applications/Media Player Classic Qute Theater.desktop' && cp -R -p usr $SNAPCRAFT_PART_INSTALL
      sed -i 's|Icon=mpc-qt|Icon=/usr/share/pixmaps/mpc-qt\.svg|' $SNAPCRAFT_PART_INSTALL/usr/share/applications/mpc-qt.desktop
    stage-packages:
      - mpv
      - libmpv1
      - ffmpeg
      - libqt5core5a
      - libqt5gui5
      - libqt5network5
      - libqt5quickwidgets5
      - libqt5x11extras5
      - libvdpau-va-gl1
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libglu1-mesa
    build-packages:
      - wget
      - rpm2cpio
      - cpio
    stage:
      - -usr/share/doc
      - -usr/share/man
      - -usr/share/lintian

apps:
  mpc-qt:
    command: desktop-launch $SNAP/usr/bin/mpc-qt
    desktop: usr/share/applications/mpc-qt.desktop
    plugs:
      - x11
      - home
      - unity7
      - network
      - desktop
      - opengl
      - wayland
      - pulseaudio
      - mount-observe
      - desktop-legacy
      - removable-media
      - screen-inhibit-control
    slots:
      - mpris
